logging:
  level:
    com.mark: DEBUG
    org.mybatis: DEBUG


##mybatis其他配置自行添加
mybatis:
  mapper-locations: classpath:mapper/*.xml

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#    username: root
#    password: qq123456
#    driver-class-name: com.mysql.jdbc.Driver